// <auto-generated />
namespace IstanbulUni.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createusertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createusertable));
        
        string IMigrationMetadata.Id
        {
            get { return "202206251142454_create-user-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
